macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

build-task:
  only_if: $CIRRUS_BRANCH == 'main'
  maven_cache:
    folder: ~/.m2
  env:
    DTHK_PLATFORM: macos
    DTHK_ARCH: aarch64
    INSTALL_DIR: ${HOME}
    GRAALVM_VERSION: 22.0.2
    GRAALVM_SLUG: 9.1
    GRAALVM_HOME: ${HOME}/graalvm-community-openjdk-${GRAALVM_VERSION}+${GRAALVM_SLUG}/Contents/Home/
    GITHUB_TOKEN: ENCRYPTED[d9d3819504334722f5d1c8e25f68922a088bef7e12b87e8c4f73482b76d7dbb6a6a83d52546031776c0c8fa4fcbded32]
  script: |
    set -euo pipefail

    # install babashka
    curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
    chmod +x install
    ./install --dir ${HOME}/.local/bin
    export PATH=${HOME}/.local/bin:$PATH

    # install clojure
    curl -L -O https://github.com/clojure/brew-install/releases/latest/download/posix-install.sh
    chmod +x posix-install.sh
    sudo ./posix-install.sh

    # install graalvm
    pushd "$INSTALL_DIR" >/dev/null
    curl -L -O https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-${GRAALVM_VERSION}/graalvm-community-jdk-${GRAALVM_VERSION}_${DTHK_PLATFORM}-${DTHK_ARCH}_bin.tar.gz
    sudo xattr -r -d com.apple.quarantine graalvm-community-jdk-${GRAALVM_VERSION}_${DTHK_PLATFORM}-${DTHK_ARCH}_bin.tar.gz
    tar -xzf graalvm-community-jdk-${GRAALVM_VERSION}_${DTHK_PLATFORM}-${DTHK_ARCH}_bin.tar.gz
    popd >/dev/null

    # prepare
    export PATH=${GRAALVM_HOME}/bin:${PATH}
    export JAVA_HOME=${GRAALVM_HOME}
    sudo /usr/sbin/softwareupdate --install-rosetta --agree-to-license
    java -version
    ${GRAALVM_HOME}bin/native-image --version
    echo $PATH
    native-image --version

    # compile
    bb ni-cli

    # test
    bb test native-image
    bb test bb-pod

    # upload artifact
    bb release native-image

  binaries_artifacts:
    path: "dist/*"
