(ns ^:no-doc datahike.index.persistent-set
  (:require [clojure.string]
            [org.replikativ.persistent-sorted-set :as psset]
            #?(:cljs [org.replikativ.persistent-sorted-set.btset :refer [BTSet]])
            #?(:cljs [org.replikativ.persistent-sorted-set.branch :refer [Branch]])
            #?(:cljs [org.replikativ.persistent-sorted-set.leaf :refer [Leaf]])
            #?(:cljs [org.replikativ.persistent-sorted-set.impl.storage :refer [IStorage]])
            [org.replikativ.persistent-sorted-set.arrays :as arrays]
            #?@(:clj  [[clojure.core.cache :as cache]
                       [clojure.core.cache.wrapped :as wrapped]]
                :cljs [[cljs.cache :as cache]
                       [cljs.cache.wrapped :as wrapped]])
            [datahike.datom :as dd :refer [index-type->cmp-quick]]
            [org.replikativ.persistent-sorted-set.fressian :as pss-fress]
            [datahike.constants :refer [tx0 txmax]]
            [datahike.index.audit :as audit :refer [IAuditable]]
            [datahike.index.interface :as di :refer [IIndex]]
            [datahike.tools :as dt]
            [konserve.core :as k]
            [konserve.serializers :refer [fressian-serializer]]
            #?(:cljs [fress.api :as fress])
            [hasch.core :refer [uuid squuid]]
            [replikativ.logging :as log])
  #?(:cljs (:require-macros [datahike.index.persistent-set :refer [generate-slice-comparator-constructor]]))
  #?(:clj (:import [datahike.datom Datom]
                   [org.fressian.handlers WriteHandler ReadHandler]
                   [org.replikativ.persistent_sorted_set PersistentSortedSet IStorage Leaf Branch ANode Settings]
                   [java.util List])))

(def index-type->kwseq
  {:eavt [:e :a :v :tx :added]
   :aevt [:a :e :v :tx :added]
   :avet [:a :v :e :tx :added]})

(defn slice-from-to-tree
  "This function generates code for deciding which datom elements that need to be compared based on which elements in the slice bounds are nil, as well as the index. Once all datom elements have been considered, `leaf-fn` is called with a vector containing the keywords of the actual elements to compare."
  [from-sym to-sym index-spec acc leaf-fn]
  (if (empty? index-spec)

    ;; When there is nothing left to compare,
    ;; return the correct comparator.
    (leaf-fn acc)

    (let [[findex & index-spec] index-spec]
      `(if (and (nil? (~findex ~from-sym))
                (nil? (~findex ~to-sym)))

         ;; Whenever both slice bounds are nil, there is nothing more to compare
         ;; and we know what comparator to return.
         ~(leaf-fn acc)

         ;; Otherwise, if at least one slie bound is non-nil, we need a comparator for
         ;; the remaining datom elements.
         ~(slice-from-to-tree from-sym to-sym index-spec (conj acc findex) leaf-fn)))))

(defn cmp-for-kwseq-sub
  "This function generates the actual body of the comparator"
  [datom0 datom1 kwseq]
  (let [result (gensym)]
    (if (empty? kwseq)
      0
      (let [[k & kwseq] kwseq]
        `(let [;; Compare the datoms at the element with key `k`
               ~result ~(dd/cmp-val-expr k datom0 datom1)]
           (cond
             ;; If it is nil, typically return 0
             (nil? ~result) 0

             ;; If it is zero, we need to proceed with the next datom element to compare.
             (zero? ~result) ~(cmp-for-kwseq-sub datom0 datom1 kwseq)

             ;; If it is non-zero, it means that this is the result of the comparison.
             :else ~result))))))

(defn cmp-for-kwseq
  "Given a sequence of keywords for datom elements to compare, generate the code for a function that performs the comparison."
  [kwseq]
  (let [datom0 (dd/type-hint-datom (gensym))
        datom1 (dd/type-hint-datom (gensym))]
    `(fn [~datom0 ~datom1] ~(cmp-for-kwseq-sub datom0 datom1 kwseq))))

(defmacro generate-slice-comparator-constructor []
  (let [index-sym (gensym)
        from-sym (gensym)
        to-sym (gensym)

        ;; List keyword sequences referring to datom elements for
        ;; all combinations of indexes and leftmost slices of the
        ;; corresponding datom elements.
        all-kwseqs (set (for [[_ kwseq] index-type->kwseq
                              limit (range 6)]
                          (vec (take limit kwseq))))
        kwseq-sym-map (zipmap all-kwseqs (repeatedly gensym))]
    `(let [;; Pre-build comparators for every sequence
           ;; of keywords referring to datom elements.
           ;; A comparator is a function taking two datoms
           ;; as arguments.
           ~@(mapcat (fn [[kwseq sym]]
                       [sym (cmp-for-kwseq kwseq)])
                     kwseq-sym-map)]

;; This is the function generated by this macro
       ;; and it is called by the `-slice` method.
       (fn [~index-sym ~from-sym ~to-sym]

         ;; First branch based on which index to use ...
         (case ~index-sym
           ~@(mapcat
              (fn [[index-key index-spec]]
                [index-key

                 ;; ... then branch based on what elements
                 ;; are non-nil in the slice bound datoms ...
                 (slice-from-to-tree
                  from-sym to-sym
                  index-spec
                  []

                  (fn [acc]
                    {:post [(symbol? %)]}

                    ;; ... and eventually return a precomputed comparator
                    ;; that will be used by `psset/slice`. The generated
                    ;; code is the symbol that is bound to a comparator.
                    (get kwseq-sym-map acc)))])
              index-type->kwseq))))))

(def slice-comparator-constructor (generate-slice-comparator-constructor))

(defn remove-datom [pset ^Datom datom index-type]
  (psset/disj pset datom (index-type->cmp-quick index-type false)))

(defn insert [pset ^Datom datom index-type]
  ;; Use lookup with prefix comparator - O(log n) with zero allocations
  ;; Prefix comparator checks only (e,a,v) to find if ANY datom exists with same triple
  (if #?(:clj (.lookup ^PersistentSortedSet pset datom (dd/index-type->cmp-prefix index-type))
         :cljs (psset/lookup pset datom (dd/index-type->cmp-prefix index-type)))
    pset
    (psset/conj pset datom (index-type->cmp-quick index-type))))

(defn temporal-insert [pset ^Datom datom index-type]
  (psset/conj pset datom (index-type->cmp-quick index-type false)))

(defn upsert [pset ^Datom datom index-type old-datom]
  (if old-datom
    (if (= index-type :avet)
      (-> pset
          (psset/disj old-datom (index-type->cmp-quick index-type))
          (psset/conj datom (index-type->cmp-quick index-type)))
      #?(:clj (.replace ^PersistentSortedSet pset old-datom datom (dd/index-type->cmp-replace index-type))
         :cljs (psset/replace pset old-datom datom (dd/index-type->cmp-replace index-type))))
    (psset/conj pset datom (index-type->cmp-quick index-type))))

(defn temporal-upsert [pset ^Datom datom index-type {old-val :v}]
  (let [{:keys [e a v tx added]} datom]
    (if added
      (if old-val
        (if (= v old-val)
          pset
          (-> pset
              (psset/conj (dd/datom e a old-val tx false)
                          (index-type->cmp-quick index-type false))
              (psset/conj datom
                          (index-type->cmp-quick index-type false))))
        (psset/conj pset datom (index-type->cmp-quick index-type false)))
      (if old-val
        (psset/conj pset
                    (dd/datom e a old-val tx false)
                    (index-type->cmp-quick index-type false))
        pset))))

(defn mark [^PersistentSortedSet pset]
  (when-not (.-_address pset)
    (throw (ex-info "Index needs to be properly flushed before marking."
                    {:type :flush-before-marking})))
  (let [addresses (atom #{})]
    (psset/walk-addresses pset (fn [address] (swap! addresses conj address)))
    @addresses))

(extend-type #?(:clj PersistentSortedSet :cljs BTSet)
  IIndex
  (-slice [^PersistentSortedSet pset from to index-type]
    (psset/slice pset from to (slice-comparator-constructor index-type from to)))
  (-lookup [^PersistentSortedSet pset key cmp]
    #?(:clj  (.lookup pset key cmp)
       :cljs (psset/lookup pset key cmp)))
  (-count-slice [^PersistentSortedSet pset from to cmp]
    (psset/count-slice pset from to cmp))
  (-has-subtree-counts? [^PersistentSortedSet pset]
    #?(:clj  (psset/has-subtree-counts? pset)
       :cljs true))
  (-all [pset]
    (identity pset))
  (-seq [^PersistentSortedSet pset]
    (seq pset))
  (-count [^PersistentSortedSet pset]
    (count pset))
  (-insert [^PersistentSortedSet pset datom index-type _op-count]
    (insert pset datom index-type))
  (-temporal-insert [^PersistentSortedSet pset datom index-type _op-count]
    (psset/conj pset datom (index-type->cmp-quick index-type)))
  (-upsert [^PersistentSortedSet pset datom index-type _op-count old-datom]
    (upsert pset datom index-type old-datom))
  (-temporal-upsert [^PersistentSortedSet pset datom index-type _op-count old-val]
    (temporal-upsert pset datom index-type old-val))
  (-remove [^PersistentSortedSet pset datom index-type _op-count]
    (remove-datom pset datom index-type))
  (-flush [^PersistentSortedSet pset _]
    (psset/store pset)
    pset)
  (-transient [^PersistentSortedSet pset]
    (transient pset))
  (-persistent! [^PersistentSortedSet pset]
    (persistent! pset))
  (-mark [^PersistentSortedSet pset]
    (mark pset)))

(defn- gen-address [^ANode node crypto-hash?]
  (if crypto-hash?
    (if (instance? Branch node)
      (uuid (vec (.addresses ^Branch node)))
      (uuid (mapv (comp vec seq) (.keys node))))
    (squuid)))  ;; Sequential UUID for better index locality

#?(:clj
   (defn- walk-pss-address!
     "Read the node at `address` directly from konserve, recompute its
      content-addressed UUID, and confirm it matches `address`. Recurses
      into Branch children, accumulating any anomalies into the
      `errors` atom (instead of throwing).

      Each error has shape:
        {:type :audit/merkle-mismatch | :audit/node-missing | :audit/unknown-node-class
         :address <expected-address>
         :recomputed <uuid?>           ;; only for :merkle-mismatch
         :node-class <class-name?>}

      `verified` holds addresses already proven good in this pass; the
      walker prunes their subtrees. Within a single tree this is a
      no-op (B-tree nodes have one parent) but it keeps the function
      composable across multiple calls sharing the same atom.

      Reads go through `k/get store` directly, bypassing the live
      `CachedStorage` LRU; otherwise a hot in-memory copy could mask a
      tampered on-disk blob."
     [store address verified errors]
     (when-not (contains? @verified address)
       (let [node (k/get store address nil {:sync? true})]
         (cond
           (nil? node)
           (swap! errors conj {:type :audit/node-missing :address address})

           :else
           (let [recomputed (cond
                              (instance? Branch node)
                              (uuid (vec (.addresses ^Branch node)))
                              (instance? Leaf node)
                              (uuid (mapv (comp vec seq) (.keys ^Leaf node))))]
             (cond
               (nil? recomputed)
               (swap! errors conj {:type :audit/unknown-node-class
                                   :address address
                                   :node-class (some-> node class .getName)})

               (not= address recomputed)
               (swap! errors conj {:type :audit/merkle-mismatch
                                   :address address
                                   :expected address
                                   :recomputed recomputed
                                   :node-class (some-> node class .getName)})

               :else
               (do
                 (when (instance? Branch node)
                   (doseq [child-addr (.addresses ^Branch node)]
                     (walk-pss-address! store child-addr verified errors)))
                 (swap! verified conj address)))))))))

(extend-type #?(:clj PersistentSortedSet :cljs BTSet)
  IAuditable
  (-merkle-root [^PersistentSortedSet pset]
    ;; gen-address (below) makes every node UUID a recursive content
    ;; hash of its datoms under :crypto-hash?, so the root _address
    ;; captures the whole tree. Set by psset/store during -flush.
    ;; Returns nil when unflushed; never throws.
    (.-_address pset))
  (-recompute-merkle-root [^PersistentSortedSet pset]
    ;; Walk the tree from konserve, deserialize each node, and confirm
    ;; its bytes hash back to its address. Konserve does NOT verify
    ;; content on read, so without this walk a tampered .ksv file would
    ;; round-trip undetected — only the in-memory `_address` would still
    ;; look correct. Returns a result map; never throws on mismatch.
    #?(:clj
       (let [address (.-_address pset)
             storage (.-_storage pset)
             store   (some-> storage :store)]
         (cond
           (nil? address)
           {:status :unsupported :reason :unflushed}
           (nil? store)
           {:status :unsupported :reason :no-store}
           :else
           (let [verified (atom #{})
                 errors   (atom [])]
             (walk-pss-address! store address verified errors)
             (if (seq @errors)
               {:status :mismatch :root nil :errors @errors}
               {:status :ok :root address}))))
       :cljs
       {:status :unsupported :reason :cljs-not-implemented})))

(defn- freelist-pop!
  "Atomically pop an address from the freelist. Returns nil if empty."
  [freelist-atom]
  (loop []
    (let [current @freelist-atom]
      (if (empty? current)
        nil
        (let [addr (peek current)
              new-list (pop current)]
          (if (compare-and-set! freelist-atom current new-list)
            addr
            (recur)))))))

(defrecord CachedStorage [store config cache stats pending-writes freed-addresses freed-set freelist cost-center-fn]
  IStorage
  (store [_ node #?(:cljs opts)]
    (@cost-center-fn :store)
    (swap! stats update :writes inc)
    (let [;; Only reuse addresses when not using crypto-hash (content-addressed storage
          ;; requires the address to match the content)
          reused (when-not (:crypto-hash? config)
                   (freelist-pop! freelist))
          address (or reused (gen-address node (:crypto-hash? config)))
          _ (log/trace :datahike/index-write {:address address :reused (boolean reused) :crypto-hash (:crypto-hash? config)})]
      ;; Evict old cached value when reusing an address
      (when reused
        (wrapped/evict cache address))
      (swap! pending-writes conj [address node])
      (wrapped/miss cache address node)
      address))
  (accessed [_ address]
    (@cost-center-fn :accessed)
    (log/trace :datahike/index-access {:address address})
    (swap! stats update :accessed inc)
    (wrapped/hit cache address)
    nil)
  (restore [_ address #?(:cljs opts)]
    (@cost-center-fn :restore)
    (log/trace :datahike/index-read {:address address})
    (if-let [cached (wrapped/lookup cache address)]
      cached
      (let [node (k/get store address nil {:sync? true})]
        (when (nil? node)
          (log/raise "Node not found in storage." {:type :node-not-found
                                                   :address address
                                                   :store store}))
        (swap! stats update :reads inc)
        (wrapped/miss cache address node)
        node)))
  (markFreed [_ address]
    (when address
      (let [now #?(:clj (java.util.Date.) :cljs (js/Date.))]
        (log/trace :datahike/index-freed {:address address})
        (swap! freed-set conj address)
        (swap! freed-addresses conj [address now]))))
  (isFreed [_ address]
    (contains? @freed-set address))
  (freedInfo [_ address]
    (when (contains? @freed-set address)
      "Address has been marked as freed")))

(def init-stats {:writes   0
                 :reads    0
                 :accessed 0})

(defn create-storage [store config]
  (CachedStorage. store config
                  (atom (cache/lru-cache-factory {} :threshold (:store-cache-size config)))
                  (atom init-stats)
                  (atom [])
                  (atom [])  ;; freed-addresses: vector of [address timestamp] pairs
                  (atom #{}) ;; freed-set: HashSet for O(1) isFreed lookups
                  (atom [])  ;; freelist: vector of reusable addresses (used as stack via peek/pop)
                  (atom (fn [_] nil))))

(def ^:const DEFAULT_BRANCHING_FACTOR 512)

;; The root meta carries `:index-type` (for the comparator) and `:storage-id` (so a wire reader
;; resolves this store's storage from pss-fress/storage-registry). In-store reads ignore
;; `:storage-id` (lexical resolver); it's there to make new roots wire-ready.
(defn- root-meta [store index-type]
  (cond-> {:index-type index-type}
    (:datahike/store-id store) (assoc pss-fress/storage-id-key (:datahike/store-id store))))

(defmethod di/empty-index :datahike.index/persistent-set [_index-name store index-type _]
  (let [^PersistentSortedSet pset (psset/sorted-set* {:comparator (index-type->cmp-quick index-type false)
                                                      :storage (:storage store)
                                                      :branching-factor (:datahike/branching-factor store DEFAULT_BRANCHING_FACTOR)})]
    (with-meta pset (root-meta store index-type))))

(defmethod di/init-index :datahike.index/persistent-set [_index-name store datoms index-type _ {:keys [indexed]}]
  (let [arr (if (= index-type :avet)
              (->> datoms
                   (filter #(contains? indexed (.-a ^Datom %)))
                   to-array)
              (cond-> datoms
                (not (arrays/array? datoms))
                (arrays/into-array)))
        _ (arrays/asort arr (index-type->cmp-quick index-type false))
        ^PersistentSortedSet pset (psset/from-sorted-array (index-type->cmp-quick index-type false)
                                                           arr
                                                           (arrays/alength arr)
                                                           {:branching-factor (:datahike/branching-factor store DEFAULT_BRANCHING_FACTOR)})]
    (set! (.-_storage pset) (:storage store))
    (with-meta pset (root-meta store index-type))))

;; Datom — datahike's domain ELEMENT type, nested inside node :keys. Its handler recurses through
;; the canonical node codec. (vector form `[e a v tx added]`, read back via datom-from-reader.)
(def ^:private datom-read-handler
  {"datahike.datom.Datom"
   #?(:clj  (reify ReadHandler (read [_ rdr _ _] (dd/datom-from-reader (.readObject rdr))))
      :cljs (fn [rdr _ _] (dd/datom-from-reader (fress/read-object rdr))))})
(def ^:private datom-write-handler
  #?(:clj  {datahike.datom.Datom {"datahike.datom.Datom"
                                  (reify WriteHandler (write [_ w d] (.writeTag w "datahike.datom.Datom" 1)
                                                        (.writeObject w (vec (seq ^Datom d)))))}}
     :cljs {datahike.datom.Datom (fn [w d] (fress/write-tag w "datahike.datom.Datom" 1)
                                   (fress/write-object w (vec (seq d))))}))

(defmethod di/add-konserve-handlers :datahike.index/persistent-set [config store]
  (let [store-id (or (get-in config [:store :id]) (:id config))  ; the konserve store's UUID
        bf       (get-in config [:index-config :branching-factor] DEFAULT_BRANCHING_FACTOR)]
    (if-let [storage-atom (:storage-atom store)]
      ;; Pre-configured (e.g. LMDB) store — handlers already attached; create + register storage.
      (let [storage (or (:storage store) (create-storage store config))]
        (reset! storage-atom storage)
        (pss-fress/register-storage! store-id storage)
        (assoc store :storage storage :datahike/store-id store-id :datahike/branching-factor bf))

      ;; Standard fressian store — attach the CANONICAL PSS serializer. The circular storage↔store
      ;; reference is broken by the registry: the root read resolves storage by this store's id from
      ;; pss-fress/storage-registry, which is populated just below (after the store is built).
      ;; LEXICAL in-store resolvers: storage = this store (by its own id); comparator = per-index via
      ;; :index-type in meta; no measure. bf self-describes per node from the blob.
      (let [node-rh (pss-fress/read-handlers {:default-bf bf})
            root-rh (pss-fress/root-read-handler
                     {:resolve-storage (fn [_] (pss-fress/registered-storage store-id))
                      :resolve-cmp     (fn [m] (index-type->cmp-quick (:index-type m) false))
                      :default-bf      bf})
            read-handlers*  (merge node-rh
                                   {pss-fress/set-tag root-rh}
                                   datom-read-handler
                                   ;; BACKWARDS COMPAT: legacy datahike.index.* tags → the canonical
                                   ;; handlers. Old {:keys}/{:level :keys :addresses :subtree-count}/
                                   ;; {:meta :address :count} are subsets; a missing :branching-factor
                                   ;; falls back to default-bf. New writes use the pss/ tags.
                                   {"datahike.index.PersistentSortedSet"        root-rh
                                    "datahike.index.PersistentSortedSet.Leaf"   (get node-rh pss-fress/leaf-tag)
                                    "datahike.index.PersistentSortedSet.Branch" (get node-rh pss-fress/branch-tag)})
            write-handlers* (merge pss-fress/write-handlers pss-fress/root-write-handlers datom-write-handler)
            store   (k/assoc-serializers store {:FressianSerializer (fressian-serializer read-handlers* write-handlers*)})
            storage (or (:storage store) (create-storage store config))]
        (pss-fress/register-storage! store-id storage)
        (assoc store :storage storage :datahike/store-id store-id :datahike/branching-factor bf)))))

(defmethod di/konserve-backend :datahike.index/persistent-set [_index-name store]
  store)

(defmethod di/default-index-config :datahike.index/persistent-set [_index-name]
  {:branching-factor DEFAULT_BRANCHING_FACTOR})
