#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

export LD_LIBRARY_PATH=./libdatahike/target
export DYLD_LIBRARY_PATH=./libdatahike/target

rm -rf "/tmp/libdatahike-test"
./libdatahike/compile-cpp
./libdatahike/target/test_cpp
